# Generated by Django 6.1.1 on 2026-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=10)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('face_status', models.CharField(blank=True, max_length=30)),
                ('face_score', models.FloatField(default=0)),
                ('forensic_score', models.IntegerField(default=0)),
                ('expiry_status', models.CharField(blank=True, max_length=30)),
                ('final_review', models.CharField(default='PENDING', max_length=30)),
            ],
        ),
    ]
